language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install  python-distutils-extra -y
script:
  - pip install -r securedrop/source-requirements.txt
  - pip install -r securedrop/document-requirements.txt
  - pip install -r securedrop/test-requirements.txt
  - ./setup_dev.sh -u
