language: python
python:
  - "2.7"
before_install: sudo apt-get install intltool -y
install: 
  - pip install http://archive.ubuntu.com/ubuntu/pool/main/p/python-distutils-extra/python-distutils-extra_2.18bzr1ubuntu0.1.tar.gz
  - pip install -r securedrop/source-requirements.txt
  - pip install -r securedrop/document-requirements.txt
  - pip install -r securedrop/test-requirements.txt
  - pip install https://mat.boum.org/files/mat-0.4.2.tar.gz
script:
  - ./setup_dev.sh -u
